blog/urls.py
from django.contrib import admin
from django.urls import path

from blog.apps import BlogConfig

from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', BlogListView.as_view(), name='list_blog'),
    path('created_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update_blog/<slug:the_slug_blog>', BlogUpdateView.as_view(), name='update_blog'),
    path('delete_blog/<slug:the_slug_blog>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('detail_blog/<slug:the_slug_blog>', BlogDetailView.as_view(), name='detail_blog'),
    path('activity_blog/<int:pk>/', BlogUpdateView.toggle_activity, name='toggle_activity_blog'),

]

companies/urls.py
from django.contrib import admin
from django.urls import path

from companies.apps import CompaniesConfig
from companies.views import CompaniesCreateView, CompaniesListView, CompaniesDetailView, CompaniesUpdateView, \
    CompaniesDeleteView

app_name = CompaniesConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create/', CompaniesCreateView.as_view(), name='create'),
    path('', CompaniesListView.as_view(), name='list'),
    path('view/<slug:the_slug_comp>/', CompaniesDetailView.as_view(), name='view'),
    path('edit/<slug:the_slug_comp>/', CompaniesUpdateView.as_view(), name='edit'),
    path('delete/<slug:the_slug_comp>/', CompaniesDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('companies/', include('companies.urls', namespace='companies')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companies/models.py
from django.db import models


class Companies(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    views_count = models.IntegerField(default=0, verbose_name='Просмотров')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Компания',
        verbose_name_plural = 'Компании'

companies/forms.py
from django import forms

from catalog.forms import StyleFormMixin
from companies.models import Companies


class CompaniesForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Companies
        fields = ('title', 'description',)

companies/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from companies.forms import CompaniesForm
from companies.models import Companies


class CompaniesCreateView(CreateView):
    model = Companies
    success_url = reverse_lazy('companies:list')
    slug_url_kwarg = 'the_slug_comp'
    form_class = CompaniesForm

    def form_valid(self, form):
        if form.is_valid():
            new_company = form.save()
            new_company.slug = slugify(new_company.title)
            new_company.save()

        return super().form_valid(form)


class CompaniesListView(ListView):
    model = Companies
    slug_url_kwarg = 'the_slug_comp'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class CompaniesDetailView(DetailView):
    model = Companies
    slug_url_kwarg = 'the_slug_comp'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class CompaniesUpdateView(UpdateView):
    model = Companies
    slug_url_kwarg = 'the_slug_comp'
    form_class = CompaniesForm

    def form_valid(self, form):
        if form.is_valid():
            new_company = form.save()
            new_company.slug = slugify(new_company.title)
            new_company.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('companies:view', args=[self.kwargs.get('the_slug_comp')])


class CompaniesDeleteView(DeleteView):
    slug_url_kwarg = 'the_slug_comp'
    model = Companies
    success_url = reverse_lazy('companies:list')

companies/templates/companies/companies_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post">
    {% csrf_token %}
    <center><p>Хотите удалить компанию "{{ object.title }}"?</p></center>
    <button type="submit" class="btn btn-danger form-control">Подтвердить</button>
    <a href="{% url 'companies:list' %}" class="btn btn-warning form-control mt-2">Отмена</a>
</form>
{% endblock %}

companies/templates/companies/companies_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}

<div class="card mb-3">
    <div class="card-body">
        <center>
            <div class="row">
                <div class="col-12">
                    <h2>{{object.title}} ({{object.slug}})</h2>
                </div>
                <div class="col-12 mt-3">
                    <p>{{object.description}}</p>
                </div>
                <a href="{% url 'companies:list' %}" class="btn btn-warning form-control">Назад</a>
            </div>
            <div class="card-footer">
                Просмотры: {{object.views_count}}
            </div>
        </center>
    </div>
</div>
{% endblock %}

companies/templates/companies/companies_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-dark form-control">
        {% if object %}
        Сохранить

        {% else %}
        Создать
        {% endif %}
    </button>
    <a href="{% url 'companies:list' %}" class="btn btn-warning form-control mt-2">Отмена</a>
</form>
{% endblock %}

companies/templates/companies/companies_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="text-center bg-secondary-subtle form-control">
    <a href="{% url 'companies:create' %}">
        <button type="button" class="btn btn-light float-end form-control">Добавить компанию</button>
    </a>
    <br><br>
    {%for object in object_list%}
    <div class="card mb-3">
        <div class="card-body">
            <center>
                <div class="row">
                    <p>
                        {{object}}
                    </p>
                    <div class="btn-group">
                        <a href="{% url 'companies:view' object.slug%}" class="btn btn-secondary">View</a>
                        <a href="{% url 'companies:edit' object.slug%}" class="btn btn-warning">Edit</a>
                        <a href="{% url 'companies:delete' object.slug%}"
                           class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </center>
        </div>
    </div>
    {%endfor%}
</div>
{% endblock %}