blog/urls.py
from django.contrib import admin
from django.urls import path

from blog.apps import BlogConfig

from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', BlogListView.as_view(), name='list_blog'),
    path('created_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update_blog/<slug:the_slug_blog>', BlogUpdateView.as_view(), name='update_blog'),
    path('delete_blog/<slug:the_slug_blog>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('detail_blog/<slug:the_slug_blog>', BlogDetailView.as_view(), name='detail_blog'),
    path('activity_blog/<int:pk>/', BlogUpdateView.toggle_activity, name='toggle_activity_blog'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('companies/', include('companies.urls', namespace='companies')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from catalog.models import NULLABLE


class Blog(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    content = models.TextField(verbose_name='Контент')
    preview = models.ImageField(upload_to='blog/%Y/%m/%d/', default='blog/none.jpg',
                                verbose_name='Изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотров')

    def __str__(self):
        return (f'Название: {self.name} / '
                f'Slug: {self.slug} / '
                f'Содержимое: {self.content} / '
                f'Изображение: {self.preview} / '
                f'Создан: {self.created_at} / '
                f'Статус: {self.is_published} / '
                f'Количество просмотров: {self.views_count}')

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ('created_at',)

blog/forms.py
from django import forms

from catalog.forms import StyleFormMixin
from blog.models import Blog


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('name', 'content', 'preview', 'is_published')

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.forms import BlogForm

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    success_url = reverse_lazy('blog:list_blog')
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.name)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    slug_url_kwarg = 'the_slug_blog'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    slug_url_kwarg = 'the_slug_blog'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    slug_url_kwarg = 'the_slug_blog'
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.name)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail_blog', args=[self.kwargs.get('the_slug_blog')])

    @staticmethod
    def toggle_activity(request, pk):
        product_items = get_object_or_404(Blog, pk=pk)
        if product_items.is_published:
            product_items.is_published = False
        else:
            product_items.is_published = True

        product_items.save()
        return redirect(reverse('blog:list_blog'))


class BlogDeleteView(DeleteView):
    model = Blog
    slug_url_kwarg = 'the_slug_blog'
    success_url = reverse_lazy('blog:list_blog')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post">
    {% csrf_token %}
    <center><p>Хотите удалить запись "{{ object.name }}"?</p></center>
    <button type="submit" class="btn btn-danger form-control">Подтвердить</button>
    <a href="{% url 'blog:list_blog' %}" class="btn btn-warning form-control mt-2">Отмена</a>
</form>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="card bg-secondary-subtle text-body-color mb-3">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <img width="450" height="400" src="{% refactor object.preview %}" class="d-block w-30">
            </div>
            <div class="col-6">
                <div class="row">
                    Заголовок:
                    <h5 class="card-title mt-3 form-control col-6">{{object.name}}</h5>
                    Опубликовано:
                    <h5 class="card-title mt-3 form-control">{{object.created_at}}</h5>
                    Просмотров:
                    <h5 class="card-title mt-3 form-control">{{object.views_count}}</h5>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mt-3">
                Контент:
                <h5 class="card-title mt-3 form-control">{{object.content}}</h5>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <a href="{% url 'blog:update_blog' object.slug %}" type="button" class="btn btn-dark form-control">Редактировать</a>
    </div>
    <div class="col-6">
        <a href="{% url 'blog:delete_blog' object.slug %}" type="button" class="btn btn-dark form-control">Удалить</a>
    </div>
</div>
<div class="row">
    <div class="col-12 mt-3">
        <a href="{% url 'blog:list_blog' %}" type="button" class="btn btn-warning form-control">Назад</a>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-warning form-control">
        {% if object %}
        Изменить
        {% else %}
        Создать
        {% endif %}
    </button>
</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="card bg-secondary-subtle text-body-color mb-3">
    <a href="{% url 'blog:create_blog' %}" type="button" class="btn btn-warning">Добавить запись</a>
    {%for object in object_list%}
    <div class="card mb-3">
        <div class="card-body">
            <center>
                <div class="row">
                    <div class="col-6">
                        Опубликовано: {{object.created_at}}
                        <h2>{{object.name}}</h2>
                        <a href="{% url 'blog:detail_blog' object.slug %}"><img width="400" height="300"
                                                                                src="{%refactor object.preview%}"
                                                                                class="d-block w-30"></a>
                    </div>
                    <div class="col-6 mt-3">
                        <h5>{{object.content | slice:"500"}}</h5>

                    </div>
                    <a href="{% url 'blog:detail_blog' object.slug %}" type="button"
                       class="btn btn-warning form-control mt-3">Прочитать
                    </a>
                    {% if object.is_published %}
                    <a href="{% url 'blog:toggle_activity_blog' object.pk %}" type="button"
                       class="btn form-control btn-warn">Деактивировать товар</a>
                    {% else %}
                    <a href="{% url 'blog:toggle_activity_blog' object.pk %}" type="button"
                       class="btn form-control btn-danger">Активировать товар</a>
                    {% endif %}
                </div>

            </center>
        </div>
    </div>
    {%endfor%}
</div>

{% endblock %}