blog/urls.py
from django.contrib import admin
from django.urls import path

from blog.apps import BlogConfig

from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', BlogListView.as_view(), name='list_blog'),
    path('created_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update_blog/<slug:the_slug_blog>', BlogUpdateView.as_view(), name='update_blog'),
    path('delete_blog/<slug:the_slug_blog>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('detail_blog/<slug:the_slug_blog>', BlogDetailView.as_view(), name='detail_blog'),
    path('activity_blog/<int:pk>/', BlogUpdateView.toggle_activity, name='toggle_activity_blog'),

]

catalog/urls.py
from django.contrib import admin
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactsListView, FeedbackCreateView, FeedbackListView, ProductListView, ProductDetailView, \
    ProductCreateView, ProductUpdateView, ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),

    path('contacts/', ContactsListView.as_view(), name='contacts'),

    path('create_feedback/', FeedbackCreateView.as_view(), name='create_feedback'),
    path('list_feedback/', FeedbackListView.as_view(), name='list_feedback'),
    path('', ProductListView.as_view(), name='index'),
    path('detail_prod/<slug:the_slug_prod>', cache_page(60)(ProductDetailView.as_view()), name='product_page'),
    path('update_prod/<slug:the_slug_prod>', ProductUpdateView.as_view(), name='update_product'),
    path('created_prod/', ProductCreateView.as_view(), name='create_product'),
    path('delete_prod/<slug:the_slug_prod>/', ProductDeleteView.as_view(), name='delete_product'),
    path('activity_prod/<int:pk>/', ProductUpdateView.toggle_activity, name='toggle_activity_prod'),
    path("category_list", CategoryListView.as_view(), name="category_list")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('companies/', include('companies.urls', namespace='companies')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views
from django.urls import path
from users.views import RegisterView, ProfileUpdateView, ProfileDetailView, ProfileDeleteView, VerifyEmailView, \
    CustomLoginView, UserPasswordResetView, UserPasswordSentView, EmailConfirmationSentView

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('user_register/', RegisterView.as_view(), name='user_register'),
    path('user_update/<int:pk>', ProfileUpdateView.as_view(), name='user_update'),
    path('user_detail/<int:pk>', ProfileDetailView.as_view(), name='user_detail'),
    path('user_delete/<int:pk>', ProfileDeleteView.as_view(), name='user_delete'),
    path("verify/<token_verify>/", VerifyEmailView.as_view(), name="verify_email"),
    path('email_confirmation_sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('user_password_sent', UserPasswordSentView.as_view(), name='user_password_sent'),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE, default='Не указано')
    first_name = models.CharField(max_length=150, default='Не указано', verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=150, default='Не указано', verbose_name='Фамилия', **NULLABLE)
    avatar = models.ImageField(upload_to='users/%Y', default='users/non_avatar.png', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULLABLE, default='Не указано')
    is_active = models.BooleanField(default=False)
    token_verify = models.UUIDField(default=uuid.uuid4, unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class CustomLoginForm(StyleFormMixin, AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput(attrs={"autofocus": True}))


class UserPasswordResetForm(StyleFormMixin, PasswordResetForm):
    class Meta:
        model = User
        fields = ('email',)

users/views.py
import random
import string

from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, TemplateView, FormView

from users.forms import UserRegisterForm, UserProfileForm, CustomLoginForm, UserPasswordResetForm
from users.models import User

from config import settings


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:email_confirmation_sent")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.instance
        self.send_verification_email(user)
        return response

    @staticmethod
    def send_verification_email(user):
        verification_link = (
            f"{settings.SITE_URL}/users/verify/{user.token_verify}/"
        )
        subject = "Подтвердите регистрацию!"
        message = (f"Благодарим за регистрацию на сайте V-magazine.\n"
                   f"Для активации учётной записи, пожалуйста перейдите по ссылке:\n"
                   f"{verification_link}")
        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [user.email],
            fail_silently=False,
        )


class VerifyEmailView(View):

    @staticmethod
    def get(request, token_verify, *args, **kwargs):
        try:
            user = User.objects.get(token_verify=token_verify)
            user.is_active = True
            user.save()
            email = user.email
            title = 'Регистрация завершена!'
            message = f"Аккаунт {email} успешно активирован!"
        except User.DoesNotExist:
            title = 'Ошибка!'
            message = "Произошла ошибка. Убедитесь, что переходите по ссылке из письма!"

        return render(request, "users/reg_confirm.html", {"message": message, 'title': title})


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User


class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('catalog:index')


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm

    def get_success_url(self):
        return reverse('users:user_detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        user = form.save()
        if user.first_name == '' or user.first_name is None:
            user.first_name = 'Не указано'
        if user.last_name == '' or user.last_name is None:
            user.last_name = 'Не указано'
        if user.phone is None:
            user.phone = 'Не указано'
        if user.country is None:
            user.country = 'Не указано'
        if user.avatar == '':
            user.avatar = 'users/non_avatar.png'
        user.save()
        return super().form_valid(form)


class CustomLoginView(LoginView):
    form_class = CustomLoginForm
    template_name = "users/login.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context


class UserPasswordResetView(FormView):
    template_name = 'users/user_password_reset.html'
    form_class = UserPasswordResetForm
    success_url = reverse_lazy('users:user_password_sent')

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        user = User.objects.filter(email=email).first()

        if user is not None:
            characters = string.ascii_letters + string.digits
            new_password = ''.join(random.choice(characters) for i in range(12))

            user.password = make_password(new_password)
            user.save()

            subject = 'Восстановление пароля'
            message = f'Ваш новый пароль: {new_password}'
            send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email])

        return super().form_valid(form)


class UserPasswordSentView(TemplateView):
    template_name = 'users/user_password_sent.html'

users/templates/users/email_confirmation_sent.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="alert alert-warning">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную
        почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="row bg-secondary-subtle text-body-color" method="post" enctype="multipart/form-data">

    <div class="card col-12 bg-secondary-subtle">
        <div class="card-header bg-secondary-subtle">
            <h3 class="card-title">
                {{title}}
            </h3>
        </div>
        <div class="card-body mb-3 mt-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-warning form-control">
                Войти
            </button>
            <a href="{% url 'users:password_reset' %}" type="button" class="btn btn-warning form-control mt-3">
                Сбросить пароль
            </a>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/reg_confirm.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="row bg-secondary-subtle text-body-color" method="post" enctype="multipart/form-data">

    <div class="card col-12 bg-secondary-subtle">
        <div class="card-header bg-secondary-subtle">
            <h3 class="card-title">
                {{ title }}
            </h3>
        </div>
        <div class="mt-4 alert alert-success form-control"><h4>{{ message }}</h4></div>
        <div class="mb-4 mt-4">
            <a href='{%url "users:login"%}' type="submit" class="btn btn-warning form-control">Авторизоваться</a>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="row bg-secondary-subtle text-body-color" method="post" enctype="multipart/form-data">

    <div class="card col-12 bg-secondary-subtle">
        <div class="card-header bg-secondary-subtle">
            <h3 class="card-title">
                {{ title }}
            </h3>
        </div>

        <div class="card-body mb-3 mt-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-warning form-control">
                Регистрация
            </button>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post">
    {% csrf_token %}
    <center><p>Хотите удалить аккаунт? "{{ object.email }}"?</p></center>
    <button type="submit" class="btn btn-danger form-control">Подтвердить</button>
    <a href="{% url 'catalog:index' %}" class="btn btn-warning form-control mt-2">Отмена</a>
</form>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<form class="row bg-secondary-subtle text-body-color" method="post" enctype="multipart/form-data">

    <div class="card bg-secondary-subtle form-control">
        <div class="card-header bg-secondary-subtle">
            <h3 class="card-title">
                Профиль
            </h3>
        </div>

        <div class="card-body mb-3 mt-3 row">
            <div class="col-6">
                <img width="300" height="300" src="{% refactor object.avatar %}">
            </div>
            <div class="col-6">
                <table>
                    <tr>
                        <th scope="row">Email:</th>
                        <td>{{object.email}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Имя:</th>
                        <td colspan="2">{{object.first_name}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Фамилия:</th>
                        <td>{{object.last_name}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Телефон:</th>
                        <td>{{object.phone}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Страна:</th>
                        <td>{{object.country}}</td>
                    </tr>
                </table>
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'users:user_update' object.pk %}" type="button"
                           class="btn btn-dark form-control">Редактировать</a>
                    </div>
                    <div class="col-6">
                        <a href="{% url 'users:user_delete' object.pk %}" type="button"
                           class="btn btn-dark form-control">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="row bg-secondary-subtle text-body-color" method="post" enctype="multipart/form-data">

    <div class="card bg-secondary-subtle form-control">
        <div class="card-header bg-secondary-subtle">
            <h3 class="card-title">
                Профиль
            </h3>
        </div>

        <div class="card-body mb-3 mt-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-warning form-control">
                Сохранить
            </button>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Сброс пароля</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-warning mt-2">Восстановить пароль</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/user_password_sent.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="alert alert-warning">
    <h4 class="alert-heading">Письмо с новым паролем отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с новым паролем. Пожалуйста, проверьте свою электронную
        почту.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}