blog/urls.py
from django.contrib import admin
from django.urls import path

from blog.apps import BlogConfig

from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', BlogListView.as_view(), name='list_blog'),
    path('created_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update_blog/<slug:the_slug_blog>', BlogUpdateView.as_view(), name='update_blog'),
    path('delete_blog/<slug:the_slug_blog>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('detail_blog/<slug:the_slug_blog>', BlogDetailView.as_view(), name='detail_blog'),
    path('activity_blog/<int:pk>/', BlogUpdateView.toggle_activity, name='toggle_activity_blog'),

]

catalog/urls.py
from django.contrib import admin
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactsListView, FeedbackCreateView, FeedbackListView, ProductListView, ProductDetailView, \
    ProductCreateView, ProductUpdateView, ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),

    path('contacts/', ContactsListView.as_view(), name='contacts'),

    path('create_feedback/', FeedbackCreateView.as_view(), name='create_feedback'),
    path('list_feedback/', FeedbackListView.as_view(), name='list_feedback'),
    path('', ProductListView.as_view(), name='index'),
    path('detail_prod/<slug:the_slug_prod>', cache_page(60)(ProductDetailView.as_view()), name='product_page'),
    path('update_prod/<slug:the_slug_prod>', ProductUpdateView.as_view(), name='update_product'),
    path('created_prod/', ProductCreateView.as_view(), name='create_product'),
    path('delete_prod/<slug:the_slug_prod>/', ProductDeleteView.as_view(), name='delete_product'),
    path('activity_prod/<int:pk>/', ProductUpdateView.toggle_activity, name='toggle_activity_prod'),
    path("category_list", CategoryListView.as_view(), name="category_list")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('companies/', include('companies.urls', namespace='companies')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    preview = models.ImageField(upload_to='catalog/%Y/%m/%d/', default='catalog/none.jpg',
                                verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    is_active = models.BooleanField(default=True, verbose_name='Признак публикации')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name="владелец", **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)
        permissions = [
            ("set_published", "Can publish product"),
            ("set_description", "Can edit description product"),
            ("set_category", "Can change category product"),
        ]


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=100, verbose_name='Описание')

    def __str__(self):
        return f'{self.name} ({self.description})'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Contacts(models.Model):
    warehouse_address = models.CharField(max_length=100, verbose_name='Адрес склада')
    legal_address = models.CharField(max_length=100, verbose_name='Юридический адрес')
    working_hours = models.CharField(max_length=100, verbose_name='Время работы')
    phone = models.CharField(max_length=100, verbose_name='Телефон')
    email = models.CharField(max_length=100, verbose_name='Электронная почта')

    def __str__(self):
        return (f'Адрес склада: {self.warehouse_address} / '
                f'Юридический адрес: {self.legal_address} / '
                f'Время работы: {self.working_hours} / '
                f'Телефон: {self.phone} / '
                f'Электронная почта: {self.email}')

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Feedback(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя')
    email = models.EmailField(max_length=150, verbose_name='Электронный адрес (email)')
    content = models.TextField(verbose_name='Сообщение')

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return f'Вам письмо от {self.email}'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='versions', verbose_name='Продукт',
                                **NULLABLE)
    title = models.CharField(max_length=150, verbose_name='Название версии')
    number_version = models.IntegerField(verbose_name='Номер версии', **NULLABLE)
    is_current = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.title} ({self.number_version})'

    class Meta:
        ordering = ['-is_current', 'number_version']
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from django.forms import BooleanField

from catalog.models import Product, Version, Feedback


class StyleFormMixin:
    """ Миксин для изменения аттрибутов стилей. """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    """ Форма для продукта """
    list_stop_word = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                      'радар']

    class Meta:
        model = Product
        # fields = '__all__'
        fields = ('name', 'description', 'preview', 'category', 'price',)
        # exclude = ('is_active',)

    def clean_name(self):
        """ Фильтрация запрещённых слов в названии """
        clean_data = self.cleaned_data['name']

        for word in self.list_stop_word:
            if word.lower() in clean_data.lower():
                raise forms.ValidationError('Данный товар запрещён к продаже')
        return clean_data

    def clean_description(self):
        """ Фильтрация запрещённых слов в описании """
        clean_data = self.cleaned_data['description']

        for word in self.list_stop_word:
            if word.lower() in clean_data.lower():
                raise forms.ValidationError('Данный товар запрещён к продаже')
        return clean_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    """ Форма для версий """
    class Meta:
        model = Version
        fields = '__all__'


class FeedbackForm(StyleFormMixin, forms.ModelForm):
    """ Форма для обратной связи """
    class Meta:
        model = Feedback
        fields = ('name', 'email', 'content')


class ProdModeratorForm(StyleFormMixin, forms.ModelForm):
    """ Форма редактирования продукта для модераторов """
    class Meta:
        model = Product
        fields = ("category", "description", "is_active",)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ValidationError, PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm, FeedbackForm, ProdModeratorForm
from catalog.models import Contacts, Product, Feedback, Version, Category
from catalog.services import get_data_from_cache


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        product_list = Product.objects.all()
        context_data['product_versions'] = {}
        for product in product_list:
            if len(product.versions.filter(is_current=True)):
                version = product.versions.filter(is_current=True).last()
                context_data['product_versions'].update({product: version})
        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if not self.request.user.groups.filter(name='Moderator').exists() and not self.request.user.is_superuser:
            queryset = queryset.filter(is_active=True)
        return queryset


class ContactsListView(ListView):
    model = Contacts


class FeedbackCreateView(CreateView):
    model = Feedback
    success_url = reverse_lazy('catalog:list_feedback')
    form_class = FeedbackForm


class FeedbackListView(ListView):
    model = Feedback


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    slug_url_kwarg = 'the_slug_prod'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        if form.is_valid():
            self.object.slug = slugify(self.object.name)
            self.object.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')
    slug_url_kwarg = 'the_slug_prod'

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        counter = 0
        self.object.slug = slugify(self.object.name)

        for form_version in formset:
            if form_version.is_valid():
                if form_version.cleaned_data.get('is_current'):
                    counter += 1

        if counter > 1:
            form.add_error(None, ValidationError('Только одна версия товара может быть активной'))
            return self.form_invalid(form)

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def form_invalid(self, form):
        context_data = self.get_context_data()
        context_data['form'] = form
        return self.render_to_response(context_data)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return ProductForm
        if user.has_perm('catalog.set_published') and user.has_perm(
                'catalog.set_description') and user.has_perm('catalog.set_category'):
            return ProdModeratorForm
        raise PermissionDenied

    @staticmethod
    def toggle_activity(request, pk):
        product_items = get_object_or_404(Product, pk=pk)
        if product_items.is_active:
            product_items.is_active = False
        else:
            product_items.is_active = True

        product_items.save()
        return redirect(reverse('catalog:index'))


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    slug_url_kwarg = 'the_slug_prod'
    success_url = reverse_lazy('catalog:index')

    def test_func(self):
        return self.request.user.is_superuser


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_data_from_cache(Category, 'category_list')
        return context_data

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Вмагазине</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="bg-light">
<div class="container">
    <div class="row">
        <div class="text-center bg-warning form-control col-3">
            <h1><img src="https://getbootstrap.com/docs/5.3/assets/brand/bootstrap-logo.svg" alt="Logo"
                     width="51" height="40"
                     class="d-inline-block"> - магазине </h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="row mt-3">
        <div class="col-3 text-center">
            {% include 'catalog/includes/inc_catalog_menu.html'%}
        </div>
        <div class="col-9">

            {% block content %}
            {% endblock %}

        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row">
        <div class="text-center bg-warning form-control col-3">
            <h6>Copyright V-magazine © {% now 'Y'%}</h6>
        </div>
    </div>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post">
    {% csrf_token %}
    <center><p>Хотите удалить запись "{{ object.name }}"?</p></center>
    <button type="submit" class="btn btn-danger form-control">Подтвердить</button>
    <a href="{% url 'catalog:list_blog' %}" class="btn btn-warning form-control mt-2">Отмена</a>
</form>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load refactor_url %}
{% block content %}
<div class="card bg-secondary-subtle text-body-color mb-3">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <img width="450" height="400" src="{% refactor object.preview %}" class="d-block w-30">
            </div>
            <div class="col-6">
                <div class="row">
                    Заголовок:
                    <h5 class="card-title mt-3 form-control col-6">{{object.name}}</h5>
                    Опубликовано:
                    <h5 class="card-title mt-3 form-control">{{object.created_at}}</h5>
                    Просмотров:
                    <h5 class="card-title mt-3 form-control">{{object.views_count}}</h5>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mt-3">
                Контент:
                <h5 class="card-title mt-3 form-control">{{object.content}}</h5>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <a href="{% url 'catalog:update_blog' object.slug %}" type="button" class="btn btn-dark form-control">Редактировать</a>
    </div>
    <div class="col-6">
        <a href="{% url 'catalog:delete_blog' object.slug %}" type="button" class="btn btn-dark form-control">Удалить</a>
    </div>
</div>
<div class="row">
    <div class="col-12 mt-3">
        <a href="{% url 'catalog:list_blog' %}" type="button" class="btn btn-warning form-control">Назад</a>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load tags %}
<div class="container">
    <div class="row">
        {% for category in category_list %}
        <div class="col-4 mt-3">
            <div class="card">
                <div class="card-body">
                    <p>Категория: {{ category.name }}</p>
                    <p>Описание: {{ category.description }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="card bg-secondary-subtle mb-3 form-control">
        <div>Контакты</div>
    </div>
    {%for object in object_list%}
    <div class="card bg-secondary-subtle text-body-color mb-2">
        <h5 class="card-title mt-3 form-control">Адрес склада: {{object.warehouse_address}}</h5>
        <h5 class="card-title mt-3 form-control">Юридический адрес: {{object.legal_address}}</h5>
        <div class="row mt-5">
            <div class="col-6">
                <p class="card-text">Телефон: {{object.phone}} <br>
                    Электронная почта: {{object.email}}</p>
            </div>
            <div class="col-6"><p>
                Режим работы: {{object.working_hours}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/feedback_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post">
    <div class="row">
        <center><h5>Напишите нам</h5></center>
    </div>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-warning form-control">Отправить</button>
</form>
{% endblock %}

catalog/templates/catalog/feedback_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="row">
    <a href="{% url 'catalog:create_feedback' %}" type="button" class="btn btn-warning form-control mb-3">Добавить
        отзыв</a>
    {%for object in object_list%}
    <div class="card bg-secondary-subtle text-body-color mb-3">

        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    Имя:
                    <h5 class="card-title mt-3 form-control col-6">{{object.name}}</h5>
                </div>
                <div class="col-6">
                    Email:
                    <h5 class="card-title mt-3 form-control col-6">{{object.email}}</h5>
                </div>
            </div>
            <div class="col-12">
                Сообщение:
                <h5 class="card-title mt-3 form-control">{{object.content}}</h5>
            </div>
        </div>

    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="bg-secondary-subtle text-body-color mb-3 form-control" method="post">
    {% csrf_token %}
    <center><p>Хотите удалить товар "{{ object.title }}"?</p></center>
    <button type="submit" class="btn btn-danger form-control">Подтвердить</button>
    <a href="{% url 'catalog:index' %}" class="btn btn-warning form-control mt-2">Отмена</a>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="card mb-3">
    <div class="row">
        <div class="col-4">
            Дата создания: {{object.created_at}}
        </div>
        <div class="col-5">
            Последнее изменение: {{object.updated_at}}
        </div>
        <div class="col-3">
            Добавил: {{object.owner}}
        </div>
    </div>
</div>
<div class="card mb-3">
    <div class="card-body">
        <div class="row text-center  ">
            <div class="col-12">
                <h2>{{object.name}}</h2>
                <img width="600" height="500" src="{% refactor object.preview %}" class="img-thumbnail">
            </div>
            <div class="col-12 mt-3 ">
                <h6>Категория: {{object.category.name}}</h6>
                <h5 class="img-thumbnail">{{object.description}}</h5>
                <h1 class="mt-5">{{object.price}} руб.</h1>
            </div>
            <button type="submit" class="btn btn-warning form-control mt-3">Добавить в корзину
            </button>
        </div>
    </div>
</div>
{% if perms.catalog.set_published and perms.catalog.set_description and perms.catalog.set_category or user == object.owner %}
<div class="card-body">
    <div class="row">
        <div class="col-6">
            <a href="{% url 'catalog:update_product' object.slug %}" type="button" class="btn btn-dark form-control">Редактировать</a>
        </div>
        {% if user.is_superuser %}
        <div class="col-6">
            <a href="{% url 'catalog:delete_product' object.slug %}" type="button" class="btn btn-dark form-control">Удалить</a>
        </div>
        {% endif %}
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-12 mt-3">
        <a href="{% url 'catalog:index' %}" type="button" class="btn btn-warning form-control mt-3 mb-3">Назад</a>
        {% if perms.catalog.set_published %} <!-- Проверка прав -->
        {% if object.is_active %} <!-- Проверка Boolean -->
        <a href="{% url 'catalog:toggle_activity_prod' object.pk%}" type="button"
           class="btn form-control btn-warn">Деактивировать товар</a>
        {% else %}
        <a href="{% url 'catalog:toggle_activity_prod' object.pk%}" type="button"
           class="btn form-control btn-danger">Активировать товар</a>
        {% endif %}
        {% endif %}
    </div>
</div>


{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="row bg-secondary-subtle text-body-color" method="post" enctype="multipart/form-data">

    <div class="card col-6 bg-secondary-subtle">
        <div class="card-header bg-secondary-subtle">
            <h3 class="card-title">
                {% if object %}
                Изменение товара
                {% else %}
                Добавить товар
                {% endif %}
            </h3>
        </div>

        <div class="card-body mb-3 mt-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-warning form-control">
                {% if object %}
                Изменить
                {% else %}
                Создать
                {% endif %}
            </button>
        </div>
    </div>
    <div class="card col-6 bg-secondary-subtle">
        {% if object %}
            {% if user == object.owner or user.is_superuser %}
            <div class="card-header bg-secondary-subtle">
                <h3 class="card-title">
                    {% if object %}
                    Измение версии
                    {% else %}
                    Добавить версию
                    {% endif %}
                </h3>
            </div>

            <div class="card-body mb-3 mt-3">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}

        {% else %}
            <div class="card-header bg-secondary-subtle">
                <h3 class="card-title">
                    {% if object %}
                    Измение версии
                    {% else %}
                    Добавить версию
                    {% endif %}
                </h3>
            </div>

            <div class="card-body mb-3 mt-3">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    </div>

</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="text-center bg-secondary-subtle form-control">
    {% if user.is_authenticated %}
    <a href="{% url 'catalog:create_product' %}">
        <button type="button" class="btn btn-light float-end">Добавить</button>
    </a>
    {% endif %}
    <h3>ТОП Новинок!</h3>
    {%for object in object_list %}
    <div class="card mb-3">
        <div class="card-body">
            <center>
                <div class="row">
                    <div class="col-6" style="max-width: 500px; height: 400px;">
                        <a href="{% url 'catalog:product_page' object.slug %}" class="link-secondary link-underline-opacity-0"><h2>{{object.name}}</h2></a>
                        <a href="{% url 'catalog:product_page' object.slug %}">
                            <img width="400" height="300" src="{%refactor object.preview%}" class="img-fluid"
                                 style="width: auto; max-height: 350px;">
                        </a>
                    </div>
                    <div class="col-6 mt-3">
                        <h6>Категория: {{object.category.name}}</h6>
                        <h5>{{object.description | slice:"100"}}... <a
                                href="{% url 'catalog:product_page' object.slug %}" class="link-secondary link-underline-opacity-0">ещё</a></h5>
                        <div class="text-center bg-secondary-subtle form-control">
                            {% if object in product_versions %}
                            <p class="mt-1 mb-1">
                                Версия: {% get_value product_versions object %}
                            </p>
                            {% else %}
                            Нет доступных версий
                            {% endif %}
                        </div>
                        <h1 class="mt-5">{{object.price}} руб.</h1>
                        {% if perms.catalog.set_published and perms.catalog.set_description and perms.catalog.set_category or user == object.owner %}
                        <div class="row">
                            <div class="col-6">
                                <a href="{% url 'catalog:update_product' object.slug %}" type="button"
                                   class="btn btn-dark form-control">Редактировать</a>
                            </div>
                            {% if user.is_superuser %}
                            <div class="col-6">
                                <a href="{% url 'catalog:delete_product' object.slug %}" type="button"
                                   class="btn btn-dark form-control">Удалить</a>
                            </div>
                            {% endif %}
                        </div>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-warning form-control mt-3">Добавить в корзину
                    </button>
                    {% if perms.catalog.set_published %} <!-- Проверка прав -->
                    {% if object.is_active %} <!-- Проверка Boolean -->
                    <a href="{% url 'catalog:toggle_activity_prod' object.pk%}" type="button"
                       class="btn form-control btn-warn">Деактивировать товар</a>
                    {% else %}
                    <a href="{% url 'catalog:toggle_activity_prod' object.pk%}" type="button"
                       class="btn form-control btn-danger">Активировать товар</a>
                    {% endif %}
                    {% endif %}
                </div>
            </center>
        </div>
    </div>
    {%endfor%}
</div>
{% endblock %}